steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '.']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter.sha256', 'gs://mongodb-exporter-${_RELEASE_TAG}/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter', 'gs://mongodb-exporter-${_RELEASE_TAG}/']

substitutions:
    _RELEASE_TAG: '0.6.1'
