steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/percona/mongodb_exporter' '/workspace/src/github.com/percona/mongodb_exporter']

- name: gcr.io/cloud-builders/git
  args: ['checkout', 'tags/${_RELEASE_TAG}']
  dir: '/workspace/src/github.com/percona/mongodb_exporter'

- name: 'gcr.io/cloud-builders/go'
  args: [ '-c', 'make' ]
  entrypoint: /bin/sh
  dir: '/workspace/src/github.com/percona/mongodb_exporter'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-c', 'sha256sum mongodb-exporter > mongodb-exporter.sha256']
  entrypoint: /bin/bash

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter.sha256', 'gs://mongodb-exporter-${_RELEASE_TAG}/']
  entrypoint: /bin/bash

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter', 'gs://mongodb-exporter-${_RELEASE_TAG}/']

substitutions:
    _RELEASE_TAG: '0.6.1'
