steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/percona/mongodb_exporter', '/usr/local/go/src/github.com/percona/mongodb_exporter']

- name: gcr.io/cloud-builders/git
  args: ['checkout', 'tags/${_RELEASE_TAG}']
  dir: '/usr/local/go/src/github.com/percona/mongodb_exporter'

- name: 'gcr.io/cloud-builders/go'
  args: [ '-c', 'make' ]
  entrypoint: /bin/sh
  dir: '/usr/local/go/src/github.com/percona/mongodb_exporter'
  env: ['PATH=/builder/home/go/bin:$PATH']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-c', 'sha256sum mongodb-exporter > mongodb-exporter.sha256']
  entrypoint: /bin/bash
  dir: '/usr/local/go/src/github.com/percona/mongodb_exporter'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter.sha256', 'gs://mongodb-exporter-${_RELEASE_TAG}/']
  entrypoint: /bin/bash
  dir: '/usr/local/go/src/github.com/percona/mongodb_exporter'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'mongodb-exporter', 'gs://mongodb-exporter-${_RELEASE_TAG}/']
  dir: '/usr/local/go/src/github.com/percona/mongodb_exporter'

substitutions:
    _RELEASE_TAG: '0.6.1'
